between many things, I did change egrep dependency to grep, updated the way the script handles the YOUTUBE_DL variable, changed to a more secure config file parser

diff --git a/radio-play b/radio-play
--- a/radio-play
+++ b/radio-play
@@ -7,7 +7,7 @@ set -e
 # modify this according to your preferences
 
 MKDIR=/usr/bin/mkdir # IMPORTANT! MKDIR executable command path (must be correctly set)
-EGREP=/usr/bin/egrep # IMPORTANT! EGREP executable command path (must be correctly set)
+SED=/usr/bin/sed # IMPORTANT! SED executable command path (must be correctly set)
 
 CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
 
@@ -31,38 +31,39 @@ PLAYER_NO_VIDEO_FLAG=--no-video
 
 
 # ALL PROGRAMS NEEDED FOR THIS SCRIPT TO WORK
-# this program was made in a Linux OS, so the needed programs may already be correctly set if you are on a Linux system (even if you are not on a Linux this dependency programs variables may be correctly set)
+# this program was made in a Linux OS, so the needed programs may already be correctly set if you are on a Linux system (even if you are not on a Linux this dependency programs variables may be correctly set by default)
 
 # YOU COULD DEFINE PROGRAMS WITH ITS CORRESPONDING FULLPATH OR JUST THE PROGRAM NAME.
 # IF YOU DEFINE JUST THE PROGRAM NAME IN ANY OF THE VARIABLES BELOW YOU ALSO HAVE TO SET THE VARIABLE: PROGRAMS_PATH (read below)
 
-YOUTUBE_DL=youtube-dl
+YOUTUBE_DL=$(/usr/bin/which youtube-dl)
 
 BASENAME=basename
 DIRNAME=dirname
 CUT=cut
 WHICH=which
-DIRNAME=dirname
 PKILL=pkill
-NOTIFY_SEND=notify-send
-SED=sed
+GREP=grep
 WC=wc
 TOUCH=touch
 CURL=curl
 HEAD=head
 RM=rm
+NOTIFY_SEND=notify-send
 
-# if you dont set the fullpath in any of the variables above (except YOUTUBE_DL), you have to define all of the variables directory names in the variable PROGRAMS_PATH below
+# if you dont set the fullpath in any of the variables above, you have to define all of the variables directories in the PROGRAMS_PATH variable that is below
 
-PROGRAMS_PATH="/usr/bin" # PATH OF THE DIRECTORY OF THE PROGRAMS ABOVE (YOUTUBE_DL variable path is the only one that will be set automatically. so no need to include it in this variable)
+PROGRAMS_PATH="/usr/bin" # PATH OF THE DIRECTORY OF THE PROGRAMS ABOVE
 ' > ${CONFIG_FILE_MAIN}
 
 	return 0
 }
 
+
 sanitize_and_import_conf_file() {
-	source <( ${EGREP} '[[:alnum:]]=[[:print:]]' $1 )
-	#source <( ${EGREP} '[[:alnum:]]=[\/"_'"'--[:alnum:]]" $1 ) # this is equivalent, not as general. works today and may work for the future
+	CFG_FILE=$1
+	CFG_CONTENT=$(${SED} -r '/[^=]+=[^=]+/!d' $CFG_FILE | ${SED} -r 's/\s+=\s/=/g')
+	eval "${CFG_CONTENT}"
 }
 
 
@@ -72,9 +73,7 @@ sanitize_and_import_conf_file() {
 sanitize_and_import_conf_file ${CONFIG_FILE_MAIN}
 
 
-YOUTUBE_DL_DIRECTORY="$(${DIRNAME} ${YOUTUBE_DL})"
-
-PATH="${PROGRAMS_PATH}:${YOUTUBE_DL_DIRECTORY}"
+PATH="${PROGRAMS_PATH}"
 
 
 [ -f ${CONFIG_FILE_RADIOS} ] && sanitize_and_import_conf_file ${CONFIG_FILE_RADIOS}
@@ -85,18 +84,32 @@ ${TOUCH} ${RECORD_FILE}
 
 # CHECK FOR PROGRAMS DEPENDENCIES
 
-## all the commands variables above (commands dependencies) for this script
-DEPS="${YOUTUBE_DL} ${MKDIR} ${EGREP} ${DIRNAME} ${BASENAME} ${CUT} ${WHICH} ${PKILL} ${SED} ${WC} ${TOUCH} ${CURL} ${HEAD} ${RM} ${NOTIFY_SEND}"
+## internal script commands dependencies
+INTERNAL_DEPS="${MKDIR} ${SED}"
 
-## add to DEPS the PLAYER_COMMAND
-DEPS+=" $(echo ${PLAYER_COMMAND} | ${CUT} -d' ' -f1)"
+## config file commands dependencies
+CONFIG_DEPS="${YOUTUBE_DL} ${BASENAME} ${DIRNAME} ${CUT} ${WHICH} ${PKILL} ${GREP} ${WC} ${TOUCH} ${CURL} ${HEAD} ${RM} ${NOTIFY_SEND}"
 
+## player dependency (read from config file)
+PLAYER_DEP="$(echo ${PLAYER_COMMAND} | ${CUT} -d' ' -f1)"
 
-for dep in $DEPS; do
-	! ${WHICH} $(${BASENAME} ${dep}) > /dev/null 2>&1 && echo -e "ERROR: command ${dep} can't be found.\nYou may need to install ${dep} to make this program work." && exit 4
-	if [ $(${DIRNAME} ${dep}) != . ]; then
+## all dependecies
+DEPS="${INTERNAL_DEPS} ${PLAYER_DEP} ${CONFIG_DEPS}"
+
+for dep in ${DEPS}; do
+	! ${WHICH} ${dep} > /dev/null 2>&1 && echo -e "ERROR: command ${dep} can't be found.\nYou may need to install ${dep} to make this program work." && exit 4
+
+	PROGRAM_DIR=$(${DIRNAME} ${dep})
+	if [ ${PROGRAM_DIR} != . ]; then
 		[ ! -f ${dep} ] && echo "ERROR: ${dep} is not a valid file in ${CONFIG_FILE_MAIN}." && exit 9
 	fi
+done
+
+# add automatically the dependecies that are set with a path
+for dep in ${CONFIG_DEPS}; do
+	PROGRAM_DIR=$(${DIRNAME} ${dep})
+	
+	[[ ${PROGRAM_DIR} = /* ]] && PATH+=":${PROGRAM_DIR}"
 done
 
 
@@ -181,7 +194,7 @@ notificate() {
 
 does_station_record_exist() {
 	ESCAPED_INPUT=$(escape $1)
-	${EGREP} -qw ${ESCAPED_INPUT} ${RECORD_FILE} && return 0 || return 1
+	${GREP} -qw ${ESCAPED_INPUT} ${RECORD_FILE} && return 0 || return 1
 }
 
 is_station_playing() {
@@ -235,7 +248,7 @@ is_string_a_url() {
 }
 
 is_url_online() {
-	${CURL} -s --head $1 | ${HEAD} -n 1 | ${EGREP} "HTTP/1.[01] [23].." > /dev/null
+	${CURL} -s --head $1 | ${HEAD} -n 1 | ${GREP} "HTTP/1.[01] [23].." > /dev/null
 	return $?
 }
 
@@ -244,6 +257,8 @@ print_help() {
 	echo -e "Usage:\n${NAME} [--help|-h] [--recreate]\n${NAME} [--video] URI\n\nThe URI can, instead, be a ${NAME}'s alias (${NAME} aliases are defined in the ${CONFIG_FILE_RADIOS} file)."
 	exit 1
 }
+
+
 
 # MAIN
 
@@ -288,6 +303,7 @@ if ! is_string_a_url ${LINK}; then
 fi
 
 STATION=${RESOURCE}
+
 
 ## check if url is not online
 
